PUT:(song1, url1):TRUE
PUT:(song1, url1):TRUE
PUT:(song2, url2):TRUE
PUT:(song1, url1):TRUE
PUT:(song2, url2):TRUE
PUT:(song1, url1):TRUE
PUT:(song2, url2):TRUE
PUT:(song3, url3):FALSE
PUT:(song4, url4):FALSE
PUT:(song5, url5):FALSE
PUT:(song1, url1):TRUE
PUT:(song1, url1):TRUE
PUT:(song2, url2):TRUE
PUT:(song3, url3):TRUE
PUT:(song4, url4):TRUE
PUT:(song5, url5):TRUE
PUT:(song1, url1):TRUE
PUT:(song2, url2):TRUE
PUT:(song3, url3):TRUE
PUT:(song4, url4):TRUE
PUT:(song5, url5):TRUE
PUT:(song1, url1):TRUE
PUT:(song2, url2):TRUE
PUT:(song3, url3):TRUE
PUT:(song4, url4):TRUE
PUT:(song5, url5):TRUE
PUT:(song3, url3):FALSE
PUT:(song4, url4):FALSE
PUT:(song5, url5):FALSE